FROM nginx:stable-alpine

# hapus default nginx page
RUN rm -rf /usr/share/nginx/html/*

# copy hasil build dari GitHub Actions
COPY dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
